// board size
const COLUMNS_COUNT = 5;
const ROWS_COUNT = 7;

const LETTER_DROP_DELAY = 100;
const PADDING = 5;
const EASY_DIFFICULTY_VALUE = 1;

// animation durations
const FALLING_DURATION = 5000;
const FAST_FORWARD_DURATION = 200;
const COLUMN_CHANGE_DURATION = 30;

export {
  COLUMNS_COUNT,
  FALLING_DURATION,
  PADDING,
  FAST_FORWARD_DURATION,
  ROWS_COUNT,
  LETTER_DROP_DELAY,
  EASY_DIFFICULTY_VALUE,
  COLUMN_CHANGE_DURATION
};
