const COLUMNS_COUNT = 5;
const ROWS_COUNT = 7;
const FALLING_DURATION = 3000;
const FAST_FORWARD_DURATION = 200;
const LETTER_DROP_DELAY = FAST_FORWARD_DURATION + 50;
const PADDING = 5;

export {
  COLUMNS_COUNT,
  FALLING_DURATION,
  PADDING,
  FAST_FORWARD_DURATION,
  ROWS_COUNT,
  LETTER_DROP_DELAY
};
